/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as ElectricityRouteImport } from './routes/electricity'
import { Route as DataRouteImport } from './routes/data'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CableRouteImport } from './routes/cable'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AirtimeRouteImport } from './routes/airtime'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as WalletFundRouteImport } from './routes/wallet.fund'
import { Route as TransactionsIdRouteImport } from './routes/transactions.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricityRoute = ElectricityRouteImport.update({
  id: '/electricity',
  path: '/electricity',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CableRoute = CableRouteImport.update({
  id: '/cable',
  path: '/cable',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AirtimeRoute = AirtimeRouteImport.update({
  id: '/airtime',
  path: '/airtime',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletFundRoute = WalletFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => WalletRoute,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/airtime': typeof AirtimeRoute
  '/analytics': typeof AnalyticsRoute
  '/bills': typeof BillsRoute
  '/business': typeof BusinessRoute
  '/cable': typeof CableRoute
  '/cards': typeof CardsRoute
  '/data': typeof DataRoute
  '/electricity': typeof ElectricityRoute
  '/merchants': typeof MerchantsRoute
  '/referrals': typeof ReferralsRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/transfers': typeof TransfersRoute
  '/wallet': typeof WalletRouteWithChildren
  '/transactions/$id': typeof TransactionsIdRoute
  '/wallet/fund': typeof WalletFundRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/airtime': typeof AirtimeRoute
  '/analytics': typeof AnalyticsRoute
  '/bills': typeof BillsRoute
  '/business': typeof BusinessRoute
  '/cable': typeof CableRoute
  '/cards': typeof CardsRoute
  '/data': typeof DataRoute
  '/electricity': typeof ElectricityRoute
  '/merchants': typeof MerchantsRoute
  '/referrals': typeof ReferralsRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/transfers': typeof TransfersRoute
  '/wallet': typeof WalletRouteWithChildren
  '/transactions/$id': typeof TransactionsIdRoute
  '/wallet/fund': typeof WalletFundRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/airtime': typeof AirtimeRoute
  '/analytics': typeof AnalyticsRoute
  '/bills': typeof BillsRoute
  '/business': typeof BusinessRoute
  '/cable': typeof CableRoute
  '/cards': typeof CardsRoute
  '/data': typeof DataRoute
  '/electricity': typeof ElectricityRoute
  '/merchants': typeof MerchantsRoute
  '/referrals': typeof ReferralsRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/transfers': typeof TransfersRoute
  '/wallet': typeof WalletRouteWithChildren
  '/transactions/$id': typeof TransactionsIdRoute
  '/wallet/fund': typeof WalletFundRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/airtime'
    | '/analytics'
    | '/bills'
    | '/business'
    | '/cable'
    | '/cards'
    | '/data'
    | '/electricity'
    | '/merchants'
    | '/referrals'
    | '/rewards'
    | '/settings'
    | '/support'
    | '/transfers'
    | '/wallet'
    | '/transactions/$id'
    | '/wallet/fund'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/airtime'
    | '/analytics'
    | '/bills'
    | '/business'
    | '/cable'
    | '/cards'
    | '/data'
    | '/electricity'
    | '/merchants'
    | '/referrals'
    | '/rewards'
    | '/settings'
    | '/support'
    | '/transfers'
    | '/wallet'
    | '/transactions/$id'
    | '/wallet/fund'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/airtime'
    | '/analytics'
    | '/bills'
    | '/business'
    | '/cable'
    | '/cards'
    | '/data'
    | '/electricity'
    | '/merchants'
    | '/referrals'
    | '/rewards'
    | '/settings'
    | '/support'
    | '/transfers'
    | '/wallet'
    | '/transactions/$id'
    | '/wallet/fund'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AirtimeRoute: typeof AirtimeRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillsRoute: typeof BillsRoute
  BusinessRoute: typeof BusinessRoute
  CableRoute: typeof CableRoute
  CardsRoute: typeof CardsRoute
  DataRoute: typeof DataRoute
  ElectricityRoute: typeof ElectricityRoute
  MerchantsRoute: typeof MerchantsRoute
  ReferralsRoute: typeof ReferralsRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TransfersRoute: typeof TransfersRoute
  WalletRoute: typeof WalletRouteWithChildren
  TransactionsIdRoute: typeof TransactionsIdRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electricity': {
      id: '/electricity'
      path: '/electricity'
      fullPath: '/electricity'
      preLoaderRoute: typeof ElectricityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cable': {
      id: '/cable'
      path: '/cable'
      fullPath: '/cable'
      preLoaderRoute: typeof CableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airtime': {
      id: '/airtime'
      path: '/airtime'
      fullPath: '/airtime'
      preLoaderRoute: typeof AirtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/fund': {
      id: '/wallet/fund'
      path: '/fund'
      fullPath: '/wallet/fund'
      preLoaderRoute: typeof WalletFundRouteImport
      parentRoute: typeof WalletRoute
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WalletRouteChildren {
  WalletFundRoute: typeof WalletFundRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletFundRoute: WalletFundRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AirtimeRoute: AirtimeRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillsRoute: BillsRoute,
  BusinessRoute: BusinessRoute,
  CableRoute: CableRoute,
  CardsRoute: CardsRoute,
  DataRoute: DataRoute,
  ElectricityRoute: ElectricityRoute,
  MerchantsRoute: MerchantsRoute,
  ReferralsRoute: ReferralsRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TransfersRoute: TransfersRoute,
  WalletRoute: WalletRouteWithChildren,
  TransactionsIdRoute: TransactionsIdRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
