/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ElectricityRouteImport } from './routes/electricity'
import { Route as DataRouteImport } from './routes/data'
import { Route as CableRouteImport } from './routes/cable'
import { Route as AirtimeRouteImport } from './routes/airtime'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as WalletFundRouteImport } from './routes/wallet.fund'
import { Route as TransactionsIdRouteImport } from './routes/transactions.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricityRoute = ElectricityRouteImport.update({
  id: '/electricity',
  path: '/electricity',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const CableRoute = CableRouteImport.update({
  id: '/cable',
  path: '/cable',
  getParentRoute: () => rootRouteImport,
} as any)
const AirtimeRoute = AirtimeRouteImport.update({
  id: '/airtime',
  path: '/airtime',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletFundRoute = WalletFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => WalletRoute,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airtime': typeof AirtimeRoute
  '/cable': typeof CableRoute
  '/data': typeof DataRoute
  '/electricity': typeof ElectricityRoute
  '/referrals': typeof ReferralsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/transactions/$id': typeof TransactionsIdRoute
  '/wallet/fund': typeof WalletFundRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airtime': typeof AirtimeRoute
  '/cable': typeof CableRoute
  '/data': typeof DataRoute
  '/electricity': typeof ElectricityRoute
  '/referrals': typeof ReferralsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/transactions/$id': typeof TransactionsIdRoute
  '/wallet/fund': typeof WalletFundRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airtime': typeof AirtimeRoute
  '/cable': typeof CableRoute
  '/data': typeof DataRoute
  '/electricity': typeof ElectricityRoute
  '/referrals': typeof ReferralsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/transactions/$id': typeof TransactionsIdRoute
  '/wallet/fund': typeof WalletFundRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airtime'
    | '/cable'
    | '/data'
    | '/electricity'
    | '/referrals'
    | '/wallet'
    | '/transactions/$id'
    | '/wallet/fund'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airtime'
    | '/cable'
    | '/data'
    | '/electricity'
    | '/referrals'
    | '/wallet'
    | '/transactions/$id'
    | '/wallet/fund'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/airtime'
    | '/cable'
    | '/data'
    | '/electricity'
    | '/referrals'
    | '/wallet'
    | '/transactions/$id'
    | '/wallet/fund'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirtimeRoute: typeof AirtimeRoute
  CableRoute: typeof CableRoute
  DataRoute: typeof DataRoute
  ElectricityRoute: typeof ElectricityRoute
  ReferralsRoute: typeof ReferralsRoute
  WalletRoute: typeof WalletRouteWithChildren
  TransactionsIdRoute: typeof TransactionsIdRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electricity': {
      id: '/electricity'
      path: '/electricity'
      fullPath: '/electricity'
      preLoaderRoute: typeof ElectricityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cable': {
      id: '/cable'
      path: '/cable'
      fullPath: '/cable'
      preLoaderRoute: typeof CableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airtime': {
      id: '/airtime'
      path: '/airtime'
      fullPath: '/airtime'
      preLoaderRoute: typeof AirtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/fund': {
      id: '/wallet/fund'
      path: '/fund'
      fullPath: '/wallet/fund'
      preLoaderRoute: typeof WalletFundRouteImport
      parentRoute: typeof WalletRoute
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WalletRouteChildren {
  WalletFundRoute: typeof WalletFundRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletFundRoute: WalletFundRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirtimeRoute: AirtimeRoute,
  CableRoute: CableRoute,
  DataRoute: DataRoute,
  ElectricityRoute: ElectricityRoute,
  ReferralsRoute: ReferralsRoute,
  WalletRoute: WalletRouteWithChildren,
  TransactionsIdRoute: TransactionsIdRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
